In [2]:
import pandas as pd

In [11]:
movies = pd.read_csv(r'D:\my_python\24_kaggle_project\archive\movie.csv')

print(type(movies))
print(movies.head(20))

<class 'pandas.DataFrame'>
    movieId                                  title  \
0         1                       Toy Story (1995)
1         2                         Jumanji (1995)
2         3                Grumpier Old Men (1995)
3         4               Waiting to Exhale (1995)
4         5     Father of the Bride Part II (1995)
5         6                            Heat (1995)
6         7                         Sabrina (1995)
7         8                    Tom and Huck (1995)
8         9                    Sudden Death (1995)
9        10                       GoldenEye (1995)
10       11         American President, The (1995)
11       12     Dracula: Dead and Loving It (1995)
12       13                           Balto (1995)
13       14                           Nixon (1995)
14       15                Cutthroat Island (1995)
15       16                          Casino (1995)
16       17           Sense and Sensibility (1995)
17       18                      Four Rooms (1995)
18       19  Ace Ventura: When Nature Calls (1995)
19       20                     Money Train (1995)

                                         genres
0   Adventure|Animation|Children|Comedy|Fantasy
1                    Adventure|Children|Fantasy
2                                Comedy|Romance
3                          Comedy|Drama|Romance
4                                        Comedy
5                         Action|Crime|Thriller
6                                Comedy|Romance
7                            Adventure|Children
8                                        Action
9                     Action|Adventure|Thriller
10                         Comedy|Drama|Romance
11                                Comedy|Horror
12                 Adventure|Animation|Children
13                                        Drama
14                     Action|Adventure|Romance
15                                  Crime|Drama
16                                Drama|Romance
17                                       Comedy
18                                       Comedy
19           Action|Comedy|Crime|Drama|Thriller

In [15]:
tags = pd.read_csv(r'D:\my_python\24_kaggle_project\archive\tag.csv')
tags.head()

   userId  movieId            tag            timestamp
0      18     4141    Mark Waters  2009-04-24 18:19:40
1      65      208      dark hero  2013-05-10 01:41:18
2      65      353      dark hero  2013-05-10 01:41:19
3      65      521  noir thriller  2013-05-10 01:39:43
4      65      592      dark hero  2013-05-10 01:41:18

In [16]:
ratings = pd.read_csv(r'D:\my_python\24_kaggle_project\archive\rating.csv')
ratings.head()

   userId  movieId  rating            timestamp
0       1        2     3.5  2005-04-02 23:53:47
1       1       29     3.5  2005-04-02 23:31:16
2       1       32     3.5  2005-04-02 23:33:39
3       1       47     3.5  2005-04-02 23:32:07
4       1       50     3.5  2005-04-02 23:29:40

In [17]:
del ratings['timestamp']
del tags['timestamp']

In [18]:
print(movies.head())
print(tags.head())
print(ratings.head())

   movieId                               title  \
0        1                    Toy Story (1995)
1        2                      Jumanji (1995)
2        3             Grumpier Old Men (1995)
3        4            Waiting to Exhale (1995)
4        5  Father of the Bride Part II (1995)

                                        genres
0  Adventure|Animation|Children|Comedy|Fantasy
1                   Adventure|Children|Fantasy
2                               Comedy|Romance
3                         Comedy|Drama|Romance
4                                       Comedy
   userId  movieId            tag
0      18     4141    Mark Waters
1      65      208      dark hero
2      65      353      dark hero
3      65      521  noir thriller
4      65      592      dark hero
   userId  movieId  rating
0       1        2     3.5
1       1       29     3.5
2       1       32     3.5
3       1       47     3.5
4       1       50     3.5

# data structure

In [19]:
row_0 = tags.iloc[0]
type(row_0)

pandas.Series

In [20]:
print(row_0)

userId              18
movieId           4141
tag        Mark Waters
Name: 0, dtype: object

In [21]:
row_0.index

Index(['userId', 'movieId', 'tag'], dtype='str')

In [22]:
row_0['userId']

np.int64(18)

In [23]:
'rating' in row_0

False

In [24]:
row_0.name

0

In [25]:
row_0 = row_0.rename('first_row')
row_0.name

'first_row'

# ▩ DataFrames

In [26]:
tags.head()

   userId  movieId            tag
0      18     4141    Mark Waters
1      65      208      dark hero
2      65      353      dark hero
3      65      521  noir thriller
4      65      592      dark hero